services:
  query:
    image: query-service
    build:
      context: .
      dockerfile: query/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - indeq-net

  # this docker setup doesn't utilize the GPU
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    environment:
      - OLLAMA_NUM_PARALLEL=4 # Number of threads to utilize
    mem_limit: 16g
    networks:
      - indeq-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    env_file:
      - ./common/config/.env
    ports:
      - 5672:5672 # AMQP protocol port
      - 15672:15672 # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - indeq-net

  authentication:
    image: authentication-service
    build:
      context: .
      dockerfile: authentication/Dockerfile
    env_file:
      - ./authentication/.env
    depends_on:
      passwordDB:
        condition: service_healthy
    networks:
      - indeq-net

  gateway:
    image: gateway-service
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      query:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - indeq-net
  waitlist:
    image: waitlist-service
    build:
      context: .
      dockerfile: waitlist/Dockerfile
    env_file:
      - ./waitlist/.env
    depends_on:
      waitlistDB:
        condition: service_healthy
    networks:
      - indeq-net
  passwordDB:
    image: postgres:latest
    env_file:
      - ./authentication/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    command:
      - -c
      - ssl=off
    expose:
      - "5432"
    volumes:
      - auth_data:/var/lib/postgresql/data
    networks:
      - indeq-net
  waitlistDB:
    image: postgres:latest
    env_file:
      - ./waitlist/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    command:
      - -c
      - ssl=off
    expose:
      - "5432"
    volumes:
      - waitlist_data:/var/lib/postgresql/data
    networks:
      - indeq-net

volumes:
  auth_data:
  waitlist_data:
  ollama_models:
  rabbitmq_data:

networks:
  indeq-net:
    driver: bridge
