services:
  query:
    image: query-service
    build:
      context: .
      dockerfile: query/Dockerfile
    env_file:
      - ./query/.env
    networks:
      - indeq-net

  authentication:
    image: authentication-service
    build:
      context: .
      dockerfile: authentication/Dockerfile
    env_file:
      - ./authentication/.env
    depends_on:
      passwordDB:
        condition: service_healthy
    networks:
      - indeq-net

  gateway:
    image: gateway-service
    build:
      context: .
      dockerfile: gateway/Dockerfile
    env_file:
      - ./gateway/.env
    ports:
      - "8080:8080"
    depends_on:
      - query
    networks:
      - indeq-net
  
  integration:
    image: integration-service
    build:
      context: .
      dockerfile: integration/Dockerfile
    env_file:
      - ./integration/.env
    depends_on:
      integrationDB:
        condition: service_healthy
    networks:
      - indeq-net
  integrationDB:
    image: postgres:latest
    env_file:
      - ./integration/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    command:
      - -c
      - ssl=off
    expose: 
      - "5432"
    volumes:
      - integration_postgres_data:/var/lib/postgresql/data
    networks:
      - indeq-net
  passwordDB:
    image: postgres:latest
    env_file:
      - ./authentication/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    command:
      - -c
      - ssl=off
    expose:
      - "5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    networks:
      - indeq-net

volumes:
  integration_postgres_data:
  auth_postgres_data:

networks:
  indeq-net:
    driver: bridge
